fix(ext/node): error formatting compatibility (#31970)
Towards #29801

Gives better error formating based on [Node's
implementation](https://github.com/nodejs/node/blob/70f6b58ac655234435a99d72b857dd7b316d34bf/lib/internal/util/inspect.js#L1661),
especially on `AggregateError` instance / nested errors. This in turn
allows
[test/parallel/test-assert-deep-with-error.js](https://github.com/nodejs/node/blob/v24.12.0/test/parallel/test-assert-deep-with-error.js)
to pass.

Given this code:

```js
class CustomError extends Error {
  constructor(message) {
    super(message);
    this.name = "CustomError";
    this.cause = new Error("This is the cause of the CustomError.");
  }
}

const aggregateError = new AggregateError([
  new CustomError("Error message 1."),
  new Error("Error message 2."),
], "Multiple errors.");
console.log(aggregateError);
```

Deno v2.6.7 outputs:

```
AggregateError: Multiple errors.
    CustomError: Error message 1.
        at file:///index.js:10:3
    Caused by Error: This is the cause of the CustomError.
        at new CustomError (file:///index.js:5:18)
        at file:///index.js:10:3 {
      name: "CustomError"
    }
    Error: Error message 2.
        at file:///index.js:11:3
    at file:///index.js:9:24

```

This PR outputs:

```
AggregateError: Multiple errors.
    at file:///index.js:9:24 {
  [errors]: [
    CustomError: Error message 1.
        at file:///index.js:10:3 {
      cause: Error: This is the cause of the CustomError.
          at new CustomError (file:///index.js:5:18)
          at file:///index.js:10:3
    },
    Error: Error message 2.
        at file:///index.js:11:3
  ]
}
```