feat(unstable): add permission broker (#30826)
This commit adds "permission broker" functionality to the CLI.

Once broker is active (using `DENO_PERMISSION_BROKER_PATH` env var), any
time a permission is checked, instead of relying on the `--allow-*` flags, a
message is sent to the broker that is responsible for granting or denying the request.

The communication is a simple JSONL protocol and it is blocking. Any
mismatch in expected format will result in process termination. If the connection
is broken the process is terminated as well.

Example program run:
```
DENO_PERMISSION_BROKER_PATH=/tmp/deno_perm_broker.sock ./target/debug/deno run test_broker.ts
-> broker req   {"v":1,"datetime":"2025-09-23T20:34:14.011647+00:00","permission":"read","value":"\"./README.md\""}
<- broker resp  {"result":"allow"}
-> broker req   {"v":1,"datetime":"2025-09-23T20:34:14.015288+00:00","permission":"read","value":"\"./Cargo.toml\""}
<- broker resp  {"result":"allow"}
-> broker req   {"v":1,"datetime":"2025-09-23T20:34:14.015659+00:00","permission":"write","value":"\"./scratch.txt\""}
<- broker resp  {"result":"allow"}
-> broker req   {"v":1,"datetime":"2025-09-23T20:34:14.016543+00:00","permission":"net","value":"\"0.0.0.0:8000\""}
<- broker resp  {"result":"allow"}
Listening on http://0.0.0.0:8000/ (http://localhost:8000/)
-> broker req   {"v":1,"datetime":"2025-09-23T20:34:14.018469+00:00","permission":"env","value":null}
<- broker resp  {"result":"deny"}
error: Uncaught (in promise) NotCapable: Requires env access, run again with the --allow-env flag
console.log("env", Deno.env.toObject());
                            ^
    at Object.toObject (ext:deno_os/30_os.js:134:12)
    at file:///Users/ib/dev/deno/test_broker.ts:10:29

```