fix(types): add [Symbol.iterator]() to NodeListOf (fixes #31382) (#31384)
This PR adds missing iterable support to `NodeListOf<TNode>` in the DOM
typings. Without this method, TypeScript raises error TS2488:

```ts
for (const child of div.childNodes) {}
// TS2488: NodeListOf<ChildNode> must have a [Symbol.iterator]() method
```