Fix build on FreeBSD
libc::TIOCGWINSZ is c_uint on FreeBSD but libc::ioctl expects a c_ulong arg

error[E0308]: mismatched types
   --> cli/ops/tty.rs:314:30
    |
314 |           if libc::ioctl(fd, libc::TIOCGWINSZ, &mut size as *mut _) != 0 {
    |                              ^^^^^^^^^^^^^^^^
    |                              |
    |                              expected `u64`, found `u32`
    |                              help: you can convert an `u32` to `u64`: `libc::TIOCGWINSZ.into()`